package googletranslator;

import com.gtranslate.Audio;
import com.gtranslate.Language;
import com.gtranslate.Translator;
import java.awt.Color;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;

public class GoogleTranslate extends javax.swing.JFrame implements Runnable{
    private Thread t;
    private Audio audio;
    private InputStream sound;
    private String from = null;
    private String to = null;
    public boolean flag1 = false;
    public boolean flag2 = false;
    public boolean flag3 = false;
    public boolean flag4 = false;
    public boolean flag5 = false;
    public boolean flag6 = false;

    public GoogleTranslate() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoogleTranslate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoogleTranslate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoogleTranslate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoogleTranslate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Google Translator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("English");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("French");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrikaans", "Albanian", "Arabic", "Armenian", "Azerbaijani", "Basque", "Belarusian", "Bengali", "Bulgarian", "Catalan", "Chinese", "Chinese_simplified", "Chinese_traditional", "Croatian", "Czech", "Danish", "Dutch", "English", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.setSelectedIndex(0);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Translate");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tamil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Hindi");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrikaans", "Albanian", "Arabic", "Armenian", "Azerbaijani", "Basque", "Belarusian", "Bengali", "Bulgarian", "Catalan", "Chinese", "Chinese_simplified", "Chinese_traditional", "Croatian", "Czech", "Danish", "Dutch", "English", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.setSelectedIndex(0);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/googletranslator/1382873628_volume-24.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    public void run(){
        Translator translate = Translator.getInstance();
            String text = translate.translate(jTextArea1.getText(), from, to);
            jTextArea2.setText(text);
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        to = Language.HINDI;
        if ((flag3 == true) || (flag6 = true)) {
            jButton4.setBackground(Color.white);
            jComboBox2.setBackground(Color.white);
            flag3 = false;
            flag6 = false;
        }
        jButton5.setBackground(Color.green);
        jButton6.setEnabled(true);
        flag4 = true;


    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        audio = Audio.getInstance();

        try {
            sound = audio.getAudio(jTextArea2.getText(), to);

            audio.play(sound);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            if (jTextArea1.getText().isEmpty()) {
                throw new Exception("Type text to translate!");
            }

            if (from == null) {
                throw new Exception("Select a source language!");

            }

            if (to == null) {
                throw new Exception("Select a target language!");
            }

            jTextArea2.setText(null);

            t=new Thread(this);
            t.start();
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }                                        


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        dispose();
        GoogleTranslate g = new GoogleTranslate();
        g.setLocationRelativeTo(null);
        g.setVisible(true);
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        from = Language.ENGLISH;

        if ((flag2 == true) || (flag5 = true)) {
            jButton2.setBackground(Color.white);
            jComboBox1.setBackground(Color.white);
            flag2 = false;
            flag5 = false;
        }
        jButton1.setBackground(Color.red);

        flag1 = true;
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        from = Language.FRENCH;
        if ((flag1 == true) || (flag5 = true)) {
            jButton1.setBackground(Color.white);
            jComboBox1.setBackground(Color.white);
            flag1 = false;
            flag5 = false;
        }
        jButton2.setBackground(Color.red);
        flag2 = true;
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        to = Language.TAMIL;
        if ((flag4 == true) || (flag6 = true)) {
            jButton5.setBackground(Color.white);
            jComboBox2.setBackground(Color.white);
            flag4 = false;
            flag6 = false;
        }
        jButton4.setBackground(Color.green);
        jButton6.setEnabled(true);
        flag3 = true;
    }                                        

                                             

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        switch (jComboBox1.getSelectedIndex()) {

            case 0:
                from = Language.AFRIKAANS;
                break;
            case 1:
                from = Language.ALBANIAN;
                break;
            case 2:
                from = Language.ARABIC;
                break;
            case 3:
                from = Language.ARMENIAN;
                break;
            case 4:
                from = Language.AZERBAIJANI;
                break;
            case 5:
                from = Language.BASQUE;
                break;
            case 6:
                from = Language.BELARUSIAN;
                break;
            case 7:
                from = Language.BENGALI;
                break;
            case 8:
                from = Language.BULGARIAN;
                break;
            case 9:
                from = Language.CATALAN;
                break;
            case 10:
                from = Language.CHINESE;
                break;
            case 11:
                from = Language.CHINESE_SIMPLIFIED;
                break;
            case 12:
                from = Language.CHINESE_TRADITIONAL;
                break;
            case 13:
                from = Language.CROATIAN;
                break;
            case 14:
                from = Language.CZECH;
                break;
            case 15:
                from = Language.DANISH;
                break;
            case 16:
                from = Language.DUTCH;
                break;
            case 17:
                from = Language.ENGLISH;
                break;
            case 18:
                from = Language.ESTONIAN;
                break;
            case 19:
                from = Language.FILIPINO;
                break;
            case 20:
                from = Language.FINNISH;
                break;
            case 21:
                from = Language.FRENCH;
                break;
            case 22:
                from = Language.GALICIAN;
                break;
            case 23:
                from = Language.GEORGIAN;
                break;
            case 24:
                from = Language.GERMAN;
                break;
            case 25:
                from = Language.GREEK;
                break;
            case 26:
                from = Language.GUJARATI;
                break;
            case 27:
                from = Language.HEBREW;
                break;
            case 28:
                from = Language.HINDI;
                break;
            case 29:
                from = Language.HUNGARIAN;
                break;
            case 30:
                from = Language.ICELANDIC;
                break;
            case 31:
                from = Language.INDONESIAN;
                break;
            case 32:
                from = Language.IRISH;
                break;
            case 33:
                from = Language.ITALIAN;
                break;
            case 34:
                from = Language.JAPANESE;
                break;
            case 35:
                from = Language.KANNADA;
                break;
            case 36:
                from = Language.KOREAN;
                break;
            case 37:
                from = Language.LATIN;
                break;
            case 38:
                from = Language.LATVIAN;
                break;
            case 39:
                from = Language.LITHUANIAN;
                break;
            case 40:
                from = Language.MACEDONIAN;
                break;
            case 41:
                from = Language.MALAY;
                break;
            case 42:
                from = Language.MALTESE;
                break;
            case 43:
                from = Language.NORWEGIAN;
                break;
            case 44:
                from = Language.PERSIAN;
                break;
            case 45:
                from = Language.POLISH;
                break;
            case 46:
                from = Language.PORTUGUESE;
                break;
            case 47:
                from = Language.ROMANIAN;
                break;
            case 48:
                from = Language.RUSSIAN;
                break;
            case 49:
                from = Language.SERBIAN;
                break;
            case 50:
                from = Language.SLOVAK;
                break;
            case 51:
                from = Language.SLOVENIAN;
                break;
            case 52:
                from = Language.SPANISH;
                break;
            case 53:
                from = Language.SWAHILI;
                break;
            case 54:
                from = Language.SWEDISH;
                break;
            case 55:
                from = Language.TAMIL;
                break;
            case 56:
                from = Language.TELUGU;
                break;
            case 57:
                from = Language.THAI;
                break;
            case 58:
                from = Language.TURKISH;
                break;
            case 59:
                from = Language.UKRAINIAN;
                break;
            case 60:
                from = Language.URDU;
                break;
            case 61:
                from = Language.VIETNAMESE;
                break;
            case 62:
                from = Language.WELSH;
                break;
            case 63:
                from = Language.YIDDISH;
                break;
        }

        if (flag1 == true || flag2 == true) {
            jButton1.setBackground(Color.white);
            jButton2.setBackground(Color.white);
            flag1 = false;
            flag2 = false;
        }
        jComboBox1.setBackground(Color.red);
        flag5 = true;

    }                                           

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        jButton6.setEnabled(true);
        switch (jComboBox2.getSelectedIndex()) {

            case 0:
                to = Language.AFRIKAANS;
                break;
            case 1:
                to = Language.ALBANIAN;
                break;
            case 2:
                to = Language.ARABIC;
                break;
            case 3:
                to = Language.ARMENIAN;
                break;
            case 4:
                to = Language.AZERBAIJANI;
                break;
            case 5:
                to = Language.BASQUE;
                break;
            case 6:
                to = Language.BELARUSIAN;
                break;
            case 7:
                to = Language.BENGALI;
                break;
            case 8:
                to = Language.BULGARIAN;
                break;
            case 9:
                to = Language.CATALAN;
                break;
            case 10:
                to = Language.CHINESE;
                break;
            case 11:
                to = Language.CHINESE_SIMPLIFIED;
                break;
            case 12:
                to = Language.CHINESE_TRADITIONAL;
                break;
            case 13:
                to = Language.CROATIAN;
                break;
            case 14:
                to = Language.CZECH;
                break;
            case 15:
                to = Language.DANISH;
                break;
            case 16:
                to = Language.DUTCH;
                break;
            case 17:
                to = Language.ENGLISH;
                break;
            case 18:
                to = Language.ESTONIAN;
                break;
            case 19:
                to = Language.FILIPINO;
                break;
            case 20:
                to = Language.FINNISH;
                break;
            case 21:
                to = Language.FRENCH;
                break;
            case 22:
                to = Language.GALICIAN;
                break;
            case 23:
                to = Language.GEORGIAN;
                break;
            case 24:
                to = Language.GERMAN;
                break;
            case 25:
                to = Language.GREEK;
                break;
            case 26:
                to = Language.GUJARATI;
                break;
            case 27:
                to = Language.HEBREW;
                break;
            case 28:
                to = Language.HINDI;
                break;
            case 29:
                to = Language.HUNGARIAN;
                break;
            case 30:
                to = Language.ICELANDIC;
                break;
            case 31:
                to = Language.INDONESIAN;
                break;
            case 32:
                to = Language.IRISH;
                break;
            case 33:
                to = Language.ITALIAN;
                break;
            case 34:
                to = Language.JAPANESE;
                break;
            case 35:
                to = Language.KANNADA;
                break;
            case 36:
                to = Language.KOREAN;
                break;
            case 37:
                to = Language.LATIN;
                break;
            case 38:
                to = Language.LATVIAN;
                break;
            case 39:
                to = Language.LITHUANIAN;
                break;
            case 40:
                to = Language.MACEDONIAN;
                break;
            case 41:
                to = Language.MALAY;
                break;
            case 42:
                to = Language.MALTESE;
                break;
            case 43:
                to = Language.NORWEGIAN;
                break;
            case 44:
                to = Language.PERSIAN;
                break;
            case 45:
                to = Language.POLISH;
                break;
            case 46:
                to = Language.PORTUGUESE;
                break;
            case 47:
                to = Language.ROMANIAN;
                break;
            case 48:
                to = Language.RUSSIAN;
                break;
            case 49:
                to = Language.SERBIAN;
                break;
            case 50:
                to = Language.SLOVAK;
                break;
            case 51:
                to = Language.SLOVENIAN;
                break;
            case 52:
                to = Language.SPANISH;
                break;
            case 53:
                to = Language.SWAHILI;
                break;
            case 54:
                to = Language.SWEDISH;
                break;
            case 55:
                to = Language.TAMIL;
                break;
            case 56:
                to = Language.TELUGU;
                break;
            case 57:
                to = Language.THAI;
                break;
            case 58:
                to = Language.TURKISH;
                break;
            case 59:
                to = Language.UKRAINIAN;
                break;
            case 60:
                to = Language.URDU;
                break;
            case 61:
                to = Language.VIETNAMESE;
                break;
            case 62:
                to = Language.WELSH;
                break;
            case 63:
                to = Language.YIDDISH;
                break;
        }

        if (flag3 == true || flag4 == true) {
            jButton4.setBackground(Color.white);
            jButton5.setBackground(Color.white);
            flag3 = false;
            flag4 = false;
        }
        jComboBox2.setBackground(Color.green);
        flag6 = true;
        if (to == Language.ARMENIAN || to == Language.AZERBAIJANI || to == Language.BASQUE || to == Language.BELARUSIAN || to == Language.BENGALI || to == Language.ESTONIAN || to == Language.FILIPINO || to == Language.GALICIAN || to == Language.GEORGIAN || to == Language.GUJARATI || to == Language.HEBREW || to == Language.IRISH || to == Language.KANNADA || to == Language.LATIN || to == Language.LITHUANIAN || to == Language.MALAY || to == Language.MALTESE || to == Language.TELUGU || to == Language.PERSIAN || to == Language.SLOVENIAN || to == Language.UKRAINIAN || to == Language.URDU || to == Language.YIDDISH) {
            jButton6.setEnabled(false);
        }
    }                                           

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {                                    
        JOptionPane.showMessageDialog(null, "Created by Rajaselvan\nr4j4531v4n@gmail.com", "About", JOptionPane.INFORMATION_MESSAGE);
    }                                   

                                         

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        dispose();
        System.exit(0);
    }                                          

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration                   

}
